version: "3"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      # - PRIVATE_KEY_PEM=your-rsa-private-key
    volumes:
      - ./src:/app/src
    command: ["run", "--allow-net", "--allow-env", "--watch", "src/main.ts"]
