version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - JWT_SECRET=your-secret-key-for-development
    volumes:
      - ./src:/app/src
    command: ["run", "--allow-net", "--allow-env", "--watch", "src/main.ts"]
