version: "3"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8801:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    command: ["run", "--allow-net", "--allow-env", "--watch", "--allow-read", "src/main.ts"]
