# fly.toml app configuration file generated for jwt-service on 2025-05-24T18:12:07+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jwt-service'
primary_region = 'nrt'

[build]
  dockerfile = 'docker/Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
